using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseSchemaReader.CodeGen
{
    public static class ColumnNameShortnener
    {
        public static string GetShortName(string columnName)
        {
            switch (columnName)
            {
                case "AccelDisconnectIndicator":
                    return "AccelDisconnect";
                case "AccelEnableIndicator":
                    return "AccelEnable";
                case "AccelerationLateralDwellValue":
                    return "AccelLateralDwell";
                case "AccelerationLateralModeIndicator":
                    return "AccelLateralMode";
                case "AccelerationLateralRateValue":
                    return "AccelLateralRate";
                case "AccelerationPedalValue":
                    return "AccelPedal";
                case "AcceleratorPedalPositionValidIndicator":
                    return "AccelPedalPositionValid";
                case "AccelLightControlValue":
                    return "AccelLightControl";
                case "AccelXAxisValue":
                    return "AccelXAxis";
                case "AccelYAxisValue":
                    return "AccelYAxis";
                case "AddressLine1Text":
                    return "AddressLine1Text";
                case "AddressLine2Text":
                    return "AddressLine2Text";
                case "AddressLine3Text":
                    return "AddressLine3Text";
                case "BendixWingmanStatusIndicator":
                    return "BendixWingmanStatus";
                case "BirthDate":
                    return "BirthDate";
                case "BrakeApplicationPressureValidIndicator":
                    return "BrakeApplicationPressureValid";
                case "BrakePressValue":
                    return "BrakePress";
                case "CityName":
                    return "CityName";
                case "ConfiguredMinimumSpeedHalfMPHValue":
                    return "ConfiguredMinimumSpeedHalfMPH";
                case "ConfiguredSlopeValue":
                    return "ConfiguredSlope";
                case "CountryCode":
                    return "CountryCode";
                case "CreatedTimestamp":
                    return "CreatedTimestamp";
                case "CreatedUserID":
                    return "CreatedUser";
                case "CruiseControlSetSpeedValidIndicator":
                    return "CruiseControlSetSpeedValid";
                case "CruiseControlStatusValidIndicator":
                    return "CruiseControlStatusValid";
                case "CruiseSpeedValue":
                    return "CruiseSpeed";
                case "CruiseStatAccelIndicator":
                    return "CruiseStatAccel";
                case "CruiseStatActiveIndicator":
                    return "CruiseStatActive";
                case "CruiseStatBrakeIndicator":
                    return "CruiseStatBrake";
                case "CruiseStatClutchIndicator":
                    return "CruiseStatClutch";
                case "CruiseStatCoastIndicator":
                    return "CruiseStatCoast";
                case "CruiseStatControlIndicator":
                    return "CruiseStatControl";
                case "CruiseStatResumeIndicator":
                    return "CruiseStatResume";
                case "CruiseStatSetIndicator":
                    return "CruiseStatSet";
                case "CustomerAssetOrganizationID":
                    return "OrgUnit";
                case "CustomerAssetOrganizationName":
                    return "OrgUnitName";
                case "CustomerContactPersonID":
                    return "ContactPerson";
                case "CustomerContactTypeIndicator":
                    return "ContactType";
                case "CustomerDeviceDescription":
                    return "Description";
                case "CustomerDeviceGroupID":
                    return "DeviceGroup";
                case "CustomerDeviceID":
                    return "Device";
                case "CustomerDriverID":
                    return "Driver";
                case "CustomerID":
                    return "Customer";
                case "CustomerLicenseDescription":
                    return "LicenseDescription";
                case "CustomerName":
                    return "Name";
                case "CustomerOnboardEventGroupID":
                    return "OnboardEventGroup";
                case "CustomerPersonGroupID":
                    return "PersonGroup";
                case "CustomerPostalAddressID":
                    return "PostalAddress";
                case "CustomerRoleCode":
                    return "RoleCode";
                case "CustomerRoleDescription":
                    return "RoleDescription";
                case "CustomerVehicleGroupID":
                    return "VehicleGroup";
                case "CustomerVehicleID":
                    return "Vehicle";
                case "CustomerVehicleUnitDescription":
                    return "UnitDescription";
                case "CustomerVehicleUnitID":
                    return "Unit";
                case "CustomerVehicleUnitName":
                    return "UnitName";
                case "DatStatGPSFixIndicator":
                    return "DatStatGPSFix";
                case "DatStatGPSQualIndicator":
                    return "DatStatGPSQual";
                case "DatStatIgnitionStatIndicator":
                    return "DatStatIgnitionStat";
                case "DatStatParkBrakeIndicator":
                    return "DatStatParkBrake";
                case "DefaultMessagesValue":
                    return "DefaultMessages";
                case "DeletedTimestamp":
                    return "DeletedTimestamp";
                case "description":
                    return "description";
                case "DeviceModelCode":
                    return "ModelCode";
                case "DeviceModelDescription":
                    return "ModelDescription";
                case "DeviceModelName":
                    return "ModelName";
                case "DeviceModelNumber":
                    return "ModelNumber";
                case "DeviceSerialNumber":
                    return "SerialNumber";
                case "DeviceSettingTemplateID":
                    return "SettingTemplate";
                case "DeviceSettingTemplateName":
                    return "SettingTemplateName";
                case "DeviceTypeCode":
                    return "TypeCode";
                case "DeviceTypeDescription":
                    return "TypeDescription";
                case "DeviceVersionNumber":
                    return "VersionNumber";
                case "DirectionHeadingCode":
                    return "DirectionHeadingCode";
                case "DirectionHeadingDegrees":
                    return "DirectionHeadingDegrees";
                case "DirectionHeadingDescription":
                    return "DirectionHeadingDescription";
                case "DistanceValue":
                    return "Distance";
                case "DriverID":
                    return "Driver";
                case "DriverLoginText":
                    return "DriverLoginText";
                case "DriversLicenseClassValue":
                    return "DriversLicenseClass";
                case "DriversLicenseExpirationDate":
                    return "DriversLicenseExpirationDate";
                case "DriversLicenseNumber":
                    return "DriversLicenseNumber";
                case "DriversLicenseStateCode":
                    return "DriversLicenseStateCode";
                case "DSTIndicator":
                    return "DST";
                case "EffectiveDate":
                    return "EffectiveDate";
                case "ElectronicAddressID":
                    return "ElectronicAddress";
                case "ElectronicAddressText":
                    return "ElectronicAddressText";
                case "ElectronicAddressTypeIndicator":
                    return "ElectronicAddressType";
                case "EndDate":
                    return "EndDate";
                case "EntityType":
                    return "EntityType";
                case "EventID":
                    return "Event";
                case "ExtendedReasonIndicator":
                    return "ExtendedReason";
                case "extent":
                    return "extent";
                case "ExternalKey":
                    return "ExternalKey";
                case "FirmwareVersionNumber":
                    return "FirmwareVersionNumber";
                case "FirstName":
                    return "FirstName";
                case "ForwardCollisionWarningPgnStatusIndicator":
                    return "ForwardCollisionWarningPgnStatus";
                case "ForwardCollisionWarningStatusIndicator":
                    return "ForwardCollisionWarningStatus";
                case "GMinusDwellValue":
                    return "GMinusDwell";
                case "GMinusModeIndicator":
                    return "GMinusMode";
                case "GMinusRateValue":
                    return "GMinusRate";
                case "GMinusSpeedValue":
                    return "GMinusSpeed";
                case "GPlusDwellValue":
                    return "GPlusDwell";
                case "GPlusModeIndicator":
                    return "GPlusMode";
                case "GPlusRateValue":
                    return "GPlusRate";
                case "GPSHeadingValue":
                    return "GPSHeading";
                case "GPSSpeedMPHValue":
                    return "GPSSpeedMPH";
                case "GPSSpeedValue":
                    return "GPSSpeed";
                case "GPSTimestamp":
                    return "GPSTimestamp";
                case "GroupDescription":
                    return "GroupDescription";
                case "GroupID":
                    return "Group";
                case "GroupName":
                    return "GroupName";
                case "HeadwayAlertPgnStatusIndicator":
                    return "HeadwayAlertPgnStatus";
                case "HeadwayDistanceValue":
                    return "HeadwayDistance";
                case "HeadwayDurationValue":
                    return "HeadwayDuration";
                case "HeadwayModeIndicator":
                    return "HeadwayMode";
                case "HeadwaySpeedHalfMPHValue":
                    return "HeadwaySpeedHalfMPH";
                case "HeadwayWarningStatusIndicator":
                    return "HeadwayWarningStatus";
                case "IgnitionStatAccessIndicator":
                    return "IgnitionStatAccess";
                case "IgnitionStatCrankIndicator":
                    return "IgnitionStatCrank";
                case "IgnitionStatRunIndicator":
                    return "IgnitionStatRun";
                case "IgnitionStatStartAidIndicator":
                    return "IgnitionStatStartAid";
                case "IgnitionSwitchValidIndicator":
                    return "IgnitionSwitchValid";
                case "InstallDate":
                    return "InstallDate";
                case "InternalKey":
                    return "InternalKey";
                case "J1708SpeedValue":
                    return "J1708Speed";
                case "JBrakePercentValue":
                    return "JBrakePercent";
                case "JBrakeStatusIndicator":
                    return "JBrakeStatus";
                case "LandmarkDescription":
                    return "LandmarkDescription";
                case "LandmarkGeoCode":
                    return "LandmarkGeoCode";
                case "LandmarkGeoFence":
                    return "LandmarkGeoFence";
                case "LandmarkID":
                    return "Landmark";
                case "LandmarkName":
                    return "LandmarkName";
                case "LastName":
                    return "LastName";
                case "LastUpdatedTimestamp":
                    return "LastUpdatedTimestamp";
                case "Location":
                    return "Location";
                case "LocationDescription":
                    return "LocationDescription";
                case "LocationTimestamp":
                    return "LocationTimestamp";
                case "LocationValue":
                    return "Location";
                case "ManualModeIndicator":
                    return "ManualMode";
                case "ManualPostSecondsValue":
                    return "ManualPostSeconds";
                case "ManualPreSecondsValue":
                    return "ManualPreSeconds";
                case "MeritorWabcoBrakeControlStatusIndicator":
                    return "MeritorWabcoBrakeControlStatus";
                case "MeritorWabcoEngineControlStatusIndicator":
                    return "MeritorWabcoEngineControlStatus";
                case "MiddleName":
                    return "MiddleName";
                case "OdometerSourceIndicator":
                    return "OdometerSource";
                case "OdometerStaleIndicator":
                    return "OdometerStale";
                case "OdometerValue":
                    return "Odometer";
                case "OEREnabledIndicator":
                    return "OEREnabled";
                case "OERReasonIndicator":
                    return "OERReason";
                case "OnboardAccelerometerEventID":
                    return "OnboardAccelerometerEvent";
                case "OnboardEventID":
                    return "OnboardEvent";
                case "OnboardEventPerSecondDataID":
                    return "OnboardEventPerSecondData";
                case "OnboardForwardCollisionEventID":
                    return "OnboardForwardCollisionEvent";
                case "OnboardTriggerSpeedEventID":
                    return "OnboardTriggerSpeedEvent";
                case "PanicModeIndicator":
                    return "PanicMode";
                case "ParentOrganizationID":
                    return "ParentOrganization";
                case "ParkingBrakeSwitchValidIndicator":
                    return "ParkingBrakeSwitchValid";
                case "PersonID":
                    return "Person";
                case "PersonPostalAddressID":
                    return "PersonPostalAddress";
                case "PostalAddressID":
                    return "PostalAddress";
                case "PostalAddressTypeIndicator":
                    return "PostalAddressType";
                case "RapidAccelerationMinumumSpeedValue":
                    return "RapidAccelMinumumSpeed";
                case "RapidAccelerationModeIndicator":
                    return "RapidAccelMode";
                case "RapidAccelerationPostSecondsValue":
                    return "RapidAccelPostSeconds";
                case "RapidAccelerationPreSecondsValue":
                    return "RapidAccelPreSeconds";
                case "RapidAccelerationSlopeValue":
                    return "RapidAccelSlope";
                case "RapidDecelerationFinalSpeedValue":
                    return "RapidDecelerationFinalSpeed";
                case "RapidDecelerationFinalTimeValue":
                    return "RapidDecelerationFinalTime";
                case "RapidDecelerationModeIndicator":
                    return "RapidDecelerationMode";
                case "RapidDecelerationPostSecondsValue":
                    return "RapidDecelerationPostSeconds";
                case "RapidDecelerationPreSecondsValue":
                    return "RapidDecelerationPreSeconds";
                case "RapidDecelerationSlopeValue":
                    return "RapidDecelerationSlope";
                case "RapidDecelerationStartSpeedValue":
                    return "RapidDecelerationStartSpeed";
                case "RegulationDescription":
                    return "RegulationDescription";
                case "RegulationID":
                    return "Regulation";
                case "RegulationName":
                    return "RegulationName";
                case "RowGUID":
                    return "RowGUID";
                case "RPMValue":
                    return "RPM";
                case "RTCTimestamp":
                    return "RTCTimestamp";
                case "SettingsDate":
                    return "SettingsDate";
                case "SlopeValue":
                    return "Slope";
                case "SocialSecurityNumber":
                    return "SocialSecurityNumber";
                case "SourceLandmarkID":
                    return "SourceLandmark";
                case "SourceSystemDescription":
                    return "SourceSystemDescription";
                case "SourceSystemID":
                    return "SourceSystem";
                case "spatial_index":
                    return "spatial_index";
                case "SpeedValue":
                    return "Speed";
                case "StabilityControlDurationValue":
                    return "StabilityControlDuration";
                case "StabilityControlModeIndicator":
                    return "StabilityControlMode";
                case "StateCode":
                    return "StateCode";
                case "TCountValue":
                    return "TCount";
                case "ThrottlePositionValidIndicator":
                    return "ThrottlePositionValid";
                case "ThrottlePositionValue":
                    return "ThrottlePosition";
                case "TimeValue":
                    return "Time";
                case "TimeZoneValue":
                    return "TimeZone";
                case "TMinusEntriesCount":
                    return "TMinusEntriesCount";
                case "TPlusEntriesCount":
                    return "TPlusEntriesCount";
                case "TranslationID":
                    return "Translation";
                case "TriggerSlopeValue":
                    return "TriggerSlope";
                case "TriggerSpeedHalfMPHValue":
                    return "TriggerSpeedHalfMPH";
                case "TriggerTypeIdentifier":
                    return "TriggerTypeIdentifier";
                case "TurnLightControlValue":
                    return "TurnLightControl";
                case "UndefinedStatusIndicator":
                    return "UndefinedStatus";
                case "UpgradeDate":
                    return "UpgradeDate";
                case "UrgentIndicator":
                    return "Urgent";
                case "VDCBrakeLightIndicator":
                    return "VDCBrakeLight";
                case "VDCInfoStatusIndicator":
                    return "VDCInfoStatus";
                case "VDCOperationStatusIndicator":
                    return "VDCOperationStatus";
                case "VDCRopBrakeIndicator":
                    return "VDCRopBrake";
                case "VDCRopEngineIndicator":
                    return "VDCRopEngine";
                case "VDCUnusedIndicator":
                    return "VDCUnused";
                case "VDCYcBrakeIndicator":
                    return "VDCYcBrake";
                case "VDCYcEngineIndicator":
                    return "VDCYcEngine";
                case "VehicleDeviceID":
                    return "VehicleDevice";
                case "VehicleID":
                    return "Vehicle";
                case "VehicleMakeID":
                    return "Make";
                case "VehicleMakeName":
                    return "MakeName";
                case "VehicleManufacturerID":
                    return "Manufacturer";
                case "VehicleManufacturerName":
                    return "ManufacturerName";
                case "VehicleModelID":
                    return "Model";
                case "VehicleModelName":
                    return "ModelName";
                case "VehicleModelYearID":
                    return "ModelYear";
                case "VehicleModelYearNumber":
                    return "ModelYearNumber";
                case "VehicleNumberText":
                    return "NumberText";
                case "VIN":
                    return "VIN";
                case "VINText":
                    return "VINText";
                case "WorkLightControlValue":
                    return "WorkLightControl";
                case "ZipCode":
                    return "ZipCode";
                default:
                    return columnName;
            }
        }
    }
}
